-- MySQL Script generated by MySQL Workbench
-- Sun 11 Oct 2015 09:58:22 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Skynet_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Skynet_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Skynet_DB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Skynet_DB` ;

-- -----------------------------------------------------
-- Table `Skynet_DB`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`students` (
  `student_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(135) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `specialization` ENUM('general', 'web', 'real_time', 'games') NULL COMMENT '',
  PRIMARY KEY (`student_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1000;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`departments` (
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`department_code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`courses` (
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `course_name` VARCHAR(45) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `credits` DECIMAL(2,1) NULL COMMENT '',
  `category` ENUM('engr_core', 'soen_core', 'comp_core', 'science', 'general_elective') NULL COMMENT '',
  PRIMARY KEY (`department_code`, `course_number`)  COMMENT '',
  INDEX `fk_courses_departments_idx` (`department_code` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_departments`
    FOREIGN KEY (`department_code`)
    REFERENCES `Skynet_DB`.`departments` (`department_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`professors` (
  `professor_id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `rating` DECIMAL(2,1) NULL COMMENT '',
  `engineer` TINYINT(1) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`professor_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`sections` (
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `professors_professor_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`section_id`, `department_code`, `course_number`)  COMMENT '',
  INDEX `fk_sections_courses1_idx` (`department_code` ASC, `course_number` ASC)  COMMENT '',
  INDEX `fk_sections_professors1_idx` (`professors_professor_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sections_courses1`
    FOREIGN KEY (`department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`courses` (`department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_professors1`
    FOREIGN KEY (`professors_professor_id`)
    REFERENCES `Skynet_DB`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`tutors` (
  `tutor_id` INT NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tutor_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`tutorials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`tutorials` (
  `tutorial_id` VARCHAR(45) NOT NULL COMMENT '',
  `tutorial_section` VARCHAR(10) NULL COMMENT '',
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `tutor_id` INT NOT NULL COMMENT '',
  INDEX `fk_tutorials_sections1_idx` (`section_id` ASC, `department_code` ASC, `course_number` ASC)  COMMENT '',
  INDEX `fk_tutorials_tutors1_idx` (`tutor_id` ASC)  COMMENT '',
  PRIMARY KEY (`tutorial_id`)  COMMENT '',
  CONSTRAINT `fk_tutorials_sections1`
    FOREIGN KEY (`section_id` , `department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`sections` (`section_id` , `department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutorials_tutors1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `Skynet_DB`.`tutors` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`labs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`labs` (
  `lab_id` VARCHAR(45) NOT NULL COMMENT '',
  `lab_section` VARCHAR(10) NULL COMMENT '',
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `tutor_id` INT NOT NULL COMMENT '',
  INDEX `fk_labs_sections1_idx` (`section_id` ASC, `department_code` ASC, `course_number` ASC)  COMMENT '',
  INDEX `fk_labs_tutors1_idx` (`tutor_id` ASC)  COMMENT '',
  PRIMARY KEY (`lab_id`)  COMMENT '',
  CONSTRAINT `fk_labs_sections1`
    FOREIGN KEY (`section_id` , `department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`sections` (`section_id` , `department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labs_tutors1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `Skynet_DB`.`tutors` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`lectures` (
  `lecture_id` VARCHAR(45) NOT NULL COMMENT '',
  `section_id` VARCHAR(10) NOT NULL COMMENT '',
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `day` ENUM('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') NULL COMMENT '',
  `start_time` TIME NULL COMMENT '',
  `end_time` TIME NULL COMMENT '',
  INDEX `fk_lectures_sections1_idx` (`section_id` ASC, `department_code` ASC, `course_number` ASC)  COMMENT '',
  PRIMARY KEY (`lecture_id`)  COMMENT '',
  CONSTRAINT `fk_lectures_sections1`
    FOREIGN KEY (`section_id` , `department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`sections` (`section_id` , `department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`enrolled_in_labs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`enrolled_in_labs` (
  `lab_id` VARCHAR(45) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`lab_id`, `student_id`)  COMMENT '',
  INDEX `fk_labs_has_students_students1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_labs_has_students_labs1_idx` (`lab_id` ASC)  COMMENT '',
  CONSTRAINT `fk_labs_has_students_labs1`
    FOREIGN KEY (`lab_id`)
    REFERENCES `Skynet_DB`.`labs` (`lab_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labs_has_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Skynet_DB`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`enrolled_in_tutorials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`enrolled_in_tutorials` (
  `tutorial_id` VARCHAR(45) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`tutorial_id`, `student_id`)  COMMENT '',
  INDEX `fk_tutorials_has_students_students1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_tutorials_has_students_tutorials1_idx` (`tutorial_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tutorials_has_students_tutorials1`
    FOREIGN KEY (`tutorial_id`)
    REFERENCES `Skynet_DB`.`tutorials` (`tutorial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutorials_has_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Skynet_DB`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`enrolled`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`enrolled` (
  `sections_section_id` VARCHAR(10) NOT NULL COMMENT '',
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `letter_grade` VARCHAR(10) NULL COMMENT '',
  `percentage_grade` DECIMAL(4,1) NULL COMMENT '',
  `gpa_attributed` DECIMAL(2,1) NULL COMMENT '',
  PRIMARY KEY (`sections_section_id`, `department_code`, `course_number`, `student_id`)  COMMENT '',
  INDEX `fk_sections_has_students_students1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_sections_has_students_sections1_idx` (`sections_section_id` ASC, `department_code` ASC, `course_number` ASC)  COMMENT '',
  CONSTRAINT `fk_sections_has_students_sections1`
    FOREIGN KEY (`sections_section_id` , `department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`sections` (`section_id` , `department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sections_has_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Skynet_DB`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Skynet_DB`.`prerequisites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Skynet_DB`.`prerequisites` (
  `department_code` VARCHAR(10) NOT NULL COMMENT '',
  `course_number` INT NOT NULL COMMENT '',
  `needs_department_code` VARCHAR(10) NOT NULL COMMENT '',
  `needs_course_number` INT NOT NULL COMMENT '',
  PRIMARY KEY (`department_code`, `course_number`, `needs_department_code`, `needs_course_number`)  COMMENT '',
  INDEX `fk_courses_has_courses_courses2_idx` (`needs_department_code` ASC, `needs_course_number` ASC)  COMMENT '',
  INDEX `fk_courses_has_courses_courses1_idx` (`department_code` ASC, `course_number` ASC)  COMMENT '',
  CONSTRAINT `fk_courses_has_courses_courses1`
    FOREIGN KEY (`department_code` , `course_number`)
    REFERENCES `Skynet_DB`.`courses` (`department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_courses_courses2`
    FOREIGN KEY (`needs_department_code` , `needs_course_number`)
    REFERENCES `Skynet_DB`.`courses` (`department_code` , `course_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

